dist: trusty
sudo: required

language: go
go_import_path: github.com/coreos/torcx
go:
  - 1.8

env:
  - ARCH=amd64 PKG=github.com/coreos/torcx VERSION=travis-dev BUILDTAGS="containers_image_openpgp" SRC_DIRS="cli pkg"

script:
- ./scripts/build.sh
- ./scripts/test.sh ${SRC_DIRS}
- make ftest
